# Create the conda environment:
# conda env create -f environment.yml -n [ecearth-outpost,ecpost,...]
#name: ecearth-outpost

channels:
  - conda-forge

dependencies:
  - python>=3.12
  - ipykernel
  - numpy
  - scipy
  - xarray
  - dask
  - cdo=2.4.0
  - netcdf4
  - nc-time-axis
  - cftime
  - matplotlib
  - seaborn
  - cartopy 
  - cmocean
  - gsw
  - psutil
  - pip
  - pip:
    - -e .
