# Create the conda environment:
# conda env create -f environment.yml -n ecearth-outpost
#name: ecearth-outpost

channels:
  - conda-forge

dependencies:
  - python==3.12
  - cdo=2.4.0
  - ipykernel
  - numpy
  - scipy
  - xarray
  - dask
  - matplotlib
  - netcdf4
  - nc-time-axis
  - cftime
  - gsw
  - psutil
  - pip
  - pip:
    - -e .
