[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ecpost"
dynamic = ["version"]
authors = [
  { name="Alessandro Sozza", email="asozza.ph@gmail.com" },
]
description = "ecearth-outpost; output post-processing tools for EC-Earth4"
readme = "README.md"
keywords = ["climate", "modeling", "diagnostics", "hpc"]
license = {file = "LICENSE"}
requires-python = ">=3.12"
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12"
]
dependencies = [
    "ruamel.yaml",
    "cdo"
]

[tool.setuptools]
py-modules = ["ecpost"]

[tool.setuptools.dynamic]
version = {file = "VERSION"}

[project.urls]
"Homepage" = "https://github.com/asozza/ecearth-outpost"
"Repository" = "https://github.com/asozza/ecearth-outpost"
"Documentation" = "https://github.com/asozza/ecearth-outpost"
"Bug Tracker" = "https://github.com/asozza/ecearth-outpost/issues"
