# workspace-config.yml — a mano, path letterali, niente template
base_path: "/ec/res4/scratch/itas/ece4/cs00"
src_path: "/ec/res4/hpcperm/itas/src/gitlab/ecearth4-v4.1.3/sources"
data_path: "/ec/res4/hpcperm/itas/data/ece-4-database"